swagger: '2.0'
info:
  description: API Clients
  version: '1.0'
  title: Clients
  contact:
    name: Leonardo Borchartt
  license:
    name: Apache Licence Version 2.0
    url: 'https://apache.org'
host: 'localhost:8083'
basePath: '/'
tags:
  - name: clients-controller
    description: Clients Controller
paths:
  /api/v1/clients:
    get:
      tags:
        - clients-controller
      summary: get
      operationId: getUsingGET
      produces:
        - 'application/json'
      responses:
        '200':
          description: OK
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Client"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
        - clients-controller
      summary: post
      operationId: postUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: client
          description: client
          required: true
          schema:
            $ref: '#/definitions/Client'
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/v1/clients/name:
    get:
      tags:
        - clients-controller
      summary: search
      operationId: searchUsingGET
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: name
          in: query
          description: name
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/api/v1/clients/{id}':
    get:
      tags:
        - clients-controller
      summary: getId
      operationId: getIdUsingGET
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    put:
      tags:
        - clients-controller
      summary: put
      operationId: putUsingPUT
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int64
        - in: body
          name: client
          description: client
          required: true
          schema:
            $ref: '#/definitions/Client'
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    delete:
      tags:
        - clients-controller
      summary: delete
      operationId: deleteUsingDELETE
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
definitions:
  Client:
    type: object
    properties:
      birthday:
        type: string
        format: date
        example: "1993-10-09"
      city:
        type: string
        example: "Floripa"
      gender:
        type: string
        example: "M"
      name:
        type: string
        example: "Leonardo Borchartt"