server:
  port: 8083
logging:
  level:
    org:
      hibernate:
        SQL: debug
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'

spring:
  datasource:
    initialization-mode: always
    #url: jdbc:mysql://localhost:3306/clients?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    url: mysql://b8146d09585265:cd1ac726@us-cdbr-iron-east-04.cleardb.net/heroku_aa6f85018e2bedb?reconnect=true

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        show_sql: true
    show-sql: true
